on:
  push:
    branches: [dev, stage, master]
  workflow_call:
    inputs:
      service-name:
        type: string
        required: true
        description: Name of the service for deployment.   

jobs:
  dev:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./jobs/cloudrun_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  stage:
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: ./jobs/cloudrun_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: stage
      ref: ${{ github.sha }}
    secrets: inherit
  prod: 
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    uses: ./jobs/cloudrun_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit