on:
  workflow_call:

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup SSH
        env:
          GIT_SSH_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.socks
        run: |
          mkdir -p ~/.ssh
          echo -n "${{ secrets.GIT_DEPLOY_KEY  }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: ssh -V

      - name: Setup Private Module
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
          go env -w GOPRIVATE=github.com/sifer169966/go-logger
          go env -w GOPROXY='https://proxy.golang.org,direct'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
