on:
  workflow_call:

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup SSH
        run: |
          sudo mkdir -p /root/.ssh
          echo -n $GIT_DEPLOY_KEY | base64 --decode > /root/.ssh/id_rsa
          sudo chmod 600 /root/.ssh/id_rsa
          ssh-keyscan github.com >> /root/.ssh/known_hosts

      - name: Setup Private Module
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
          go env -w GOPRIVATE=gitlab.bitkub.io/*
          go env -w GOPROXY=direct

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
