on:
  workflow_call:

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo -e ${{ secrets.GIT_DEPLOY_KEY  }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Set GIT_SSH
        run: echo "export GIT_SSH=\$(which ssh)" >> $GITHUB_ENV

      - name: Debug SSH Key
        run: ssh-add -l

      - name: Setup Private Module
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
          go env -w GOPRIVATE=github.com/sifer169966/go-logger
          go env -w GOPROXY=direct

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
