on:
  workflow_call:

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: github.com
          key: ${{ secrets.GIT_DEPLOY_KEY }}

      # - name: Setup SSH
      #   run: |
      #     eval "$(ssh-agent -s)"
      #     mkdir -p ~/.ssh
      #     echo -n ${{ secrets.GIT_DEPLOY_KEY  }} | tr -d '\r' > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Private Module
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
          go env -w GOPRIVATE=github.com/sifer169966/*
          go env -w GOPROXY=direct

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
