on:
  workflow_call:
    secrets:
      GIT_DEPLOY_KEY:
        required: true
        description: github ssh key to access private repo.   

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo -n ${{ secrets.GIT_DEPLOY_KEY }} | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: ssh -V

      - name: Setup Private Module
        run: |
          git config --global url."git@github.com:sifer169966".insteadOf https://github.com/sifer169966/
          go env -w GOPRIVATE=github.com/sifer169966/go-logger
          go env -w GOPROXY='https://proxy.golang.org,direct'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
