on:
  workflow_call:
    inputs:
      service-name:
        type: string
        required: true
        description: application name
jobs:
  go-quality-verification:
    name: golang quality gate
    uses: ./.github/workflows/go_quality_verification.yml
    secrets: inherit
  dev:
    name: deploy application to dev environment
    needs: go-quality-verification
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/jobs/build_image.yml
    with: 
      service-name: ${{ inputs.service-name }}
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  sit:
    name: deploy application to sit environment
    needs: go-quality-verification
    if: ${{ startsWith(github.ref,'refs/heads/release/')  || startsWith(github.ref,'refs/heads/hotfix/') }}
    uses: ./.github/workflows/jobs/build_image.yml
    with: 
      service-name: ${{ inputs.service-name }}
      environment: sit
      ref: ${{ github.sha }}
    secrets: inherit
  stg:
    name: deploy application to staging environment
    needs: go-quality-verification
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    uses: ./.github/workflows/jobs/build_image.yml
    with:
      service-name: ${{ inputs.service-name }}
      environment: stg
      ref: ${{ github.sha }}
    secrets: inherit