on:
  workflow_call:
    # secrets:
    #   GIT_DEPLOY_KEY:
    #     required: true
    #     description: github ssh key to access private repo.   
    #   GCP_PROJECT_ID:
    #     required: true
    #     description: GCP Project ID.    
    #   GCP_REGION:  
    #     required: true
    #     description: GCP Target Region.
    #   GOOGLE_APPLICATION_CREDENTIALS:
    #     required: true
    #     description: GCP Service Account.
    inputs:
      service-name:
        type: string
        required: true
        description: application name
      ref:
        type: string
        required: true
        description: git commit
jobs:
  ci:
    uses: sfier-playground/github-action-share-template/.github/workflows/go_ci.yml@master
    secrets: inherit
    # secrets:
    #   GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
  dev:
    needs: ci
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: sfier-playground/github-action-share-template/.github/workflows/cloud_run_deployment.yml@master
    with: 
      environment: dev
      ref: ${{ inputs.sha }}
    secrets: inherit
  stage:
    needs: ci
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: sfier-playground/github-action-share-template/.github/workflows/cloud_run_deployment.yml@master
    with: 
      environment: stage
      ref: ${{ inputs.sha }}
    secrets: inherit
  prod:
    needs: ci
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    uses: sfier-playground/github-action-share-template/.github/workflows/cloud_run_deployment.yml@master
    # permissions: 
    #   id-token: write
    #   contents: read
    with:
      environment: prod
      ref: ${{ inputs.sha }}
    secrets: inherit