on:
  workflow_call:
    # inputs:
    #   service-name:
    #     type: string
    #     required: true
    #     description: Name of the service for deployment.   

jobs:
  ci:
    uses: sfier-playground/github-action-share-template/.github/workflows/go_ci.yml@master
  dev:
    needs: ci
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: sfier-playground/github-action-share-template/.github/workflows/cloud_run_deployment.yml@master
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  stage:
    needs: ci
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: sfier-playground/github-action-share-template/.github/workflows/cloud_run_deployment.yml@master
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: stage
      ref: ${{ github.sha }}
    secrets: inherit
  prod:
    needs: ci
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    uses: sfier-playground/github-action-share-template/.github/workflows/cloud_run_deployment.yml@master
    permissions: 
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit